version: "3.8"

services:
  app:
    build: .
    image: exp_frontend
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

