export let Constants = {
  Trip: {
    Prefrences: {
      initialValues: {
        prefix_string: "Trip-1",
        next_number: "00022",
        allow_only_expenses_within_trip_range: true,
        can_create_advance_on_approval: false,
        allowance_type: "all trips",
        can_attach_trip_pdf_in_mail: true,
        is_cc_required_on_submit: true,
        cc_email_on_submit: "",
        term: true,
        enable_self_approval: true,
        is_cc_required_on_approval: true,
        cc_email_on_approval: "",
        can_notify_on_approval: false,
        can_notify_on_submit: false,
        can_notify_on_cancel: false,
      },
    },
    Fields: {
      initialValues: {
        business_purpose: true,
        billable: false,
        customer: true,
        project: false,
        meal_preference: true,
        seat_preference: false,
        budget_amount: true,
        other_travelers: false,
        personal: true,
        is_visa_required: false,
        is_international: true,
        flight_reservation: false,
        hotel_reservation: true,
        car_rentals: false,
        bus: true,
        train: false,
        ferry: true,
      },
      label_field: [
        { value: "business_purpose", label: "Business Purpose" },
        { value: "billable", label: "Billable" },
        { value: "customer", label: "Customer" },
        { value: "project", label: "Project" },
        { value: "meal_preference", label: "Meal Preference" },
        { value: "seat_preference", label: "Seat Preference" },
        { value: "budget_amount", label: "Budget amount" },
        { value: "other_travelers", label: "Other Travelers" },
        { value: "personal", label: "Personal" },
        { value: "is_visa_required", label: "Is visa required" },
        { value: "is_international", label: "Is International" },
        { value: "flight_reservation", label: "Flight Reservation" },
        { value: "hotel_reservation", label: "Hotel Reservation" },
        { value: "car_rentals", label: "Car Rentals" },
        { value: "bus", label: "Bus" },
        { value: "train", label: "Train" },
        { value: "ferry", label: "Ferry" },
      ],
    },
  },
  Expense: {
    Prefrences: {
      initialValues: {
        mark_expense_as_reimbursable: false,
        is_expense_aging_required: true,
        maximum_expense_age: 15,
      },
      content: [
        {
          label: "Create reimbursable expenses by default",
          value: "mark_expense_as_reimbursable",
        },
        {
          label: "Set the expense expiry period to mention Days",
          value: "is_expense_aging_required",
          field: true,
          type: "numberField",
          name: "maximum_expense_age",
        },
      ],
    },
  },
};
