/** @format */

export const Labels = {
  LOGIN: "Login",
  SIGNUP: "SIGNUP",
  EMAIL: "Email",
  PASSWORD: "Password",
  ENTER: "Enter",
  FORGET: "Forget",
  GENDER: "gender",
  REMEMBER_ME: "Remember me",
  SUBMIT: "Submit",
  SIGNIN: "Sign In",
  CODE: "Code",
  CONFIRM_PASSWROD: "Confirm Password",
  NAME: "Name",
  REGISTER_ORGANIZATION: "register-organization",
  CREATE: "Create",
  BACK: "Back",
  NEXT: "Next",
  TYPE: "Type",
  TIMEZONE: "Timezone",
  FISCAL_YEAR: "Fiscal Year",
  BASE_CURRENCY: "Base Currency",
  LICENSE_NO: "License No",
  START_DATE: "Start Date",
  CONTACT: "Contact",
  COUNTRY: "Country",
  STATE: "State/Province",
  CITY: "City",
  ZIP_CODE: "Zip Code",
  ADDRESS: "Address",
  PHONE: "Phone",
  WEBSITE: "Website",
  NEW_CURRENCY: "New Currency",
  CURRENCY_CODE: "Currency Code",
  SYMBOL: "Symbol",
  EXCHANGE_RATE: "Exchange Rate",
  CANCEL: "Cancel",
  YES: "Yes",
  NO: "No",
  DELETE: "Delete",
  _CURRENCY: "Currency",
  SET_AS_DEFAULT: "Set as Default",
  OWNER: "Owner",
  INVITEE: "Invitee",
  BUSINESS_INFO: "Business Info",
  CONTACT_INFO: "Contact Info",
  BUSINESS_NAME: "Business Name",
  TAX: "Tax",
  RATE: "Rate",
  NEW_TAX: "New Tax",
  GROUP: "Group",
  TAX_RATE: "Tax Rates",
  USERS_ROLES: "Users & Roles",
  _DASHBOARD: "Dashboard",
  _ORGANIZATION_PROFILE: "Organization Profile",
  _TAXES: "Taxes",
  SETTINGS: "Settings",
  COMPOUND_TAX: "Yes, this tax is a compound tax",
  BUSINESSES: "Manage Businesses",
  NEW_MEAL_PREFERENCE: "New Meal Preference",
  NEW_SEAT_PREFERENCE: "New Seat Preference",
  NEW_FLIGHT_PREFERENCE: "New Flight Preference",
  NEW_TIME_PREFERENCE: "New Time Preference",
  NEW_CAR_TYPE_PREFERENCE: "New Car Type Preference",
  MEAL_PREFERENCE: "Meal Preference",
  SEAT_PREFERENCE: "Seat Preference",
  FLIGHT_PREFERENCE: "Flight Preference",
  TIME_PREFERENCE: "Time Preference",
  CAR_TYPE_PREFERENCE: "Car Preference",
  _TRIPS: "Trips",
  NEW_TRIP_LABEL: "New Trip",
  TRIP_NUMBER:"Trip#",
  _APPROVALS: "Approvals",
  GO_BACk: "Go Back",
  _EXPENSES: "Expenses",
  EXPENSE: "Expense",
  _NEW_EXPENSE: "New Expense",
  NEW_TAG: "Create New Tag",
  TAG: "Tag",
  _PAYMENT_MODES: "Payment Modes",
  Create_New_PaidThrough: "Create New Paid Through",
  REPORTS: "Reports",
  REPORT: "Report",
  New_REPORT: "New Report",
  REPORT_NAME:"Report Name",
  REPORT_NUMBER:"Report#",
  STATUS:"Status",
  APPROVER:"Approver",
  TOTAL:"Total",
  AMOUNT:"Amount",
  TO_BE_REIMBURSED:"To Be Rimbursed",
  BUSINESS_PURPOSE:"Business Purpose",
  DATE:"date",
  REFERENCE_NUMBER:"Reference#",
  HOME: "Home",
  ANALYTICS: "Analytics",
  Activity: "Activity",
  NEW_MERCHANT_LABEL: "New Merchant",
  MERCHANT_NAME: "Merchant Name",
  MERCHANT_CODE: "Merchant Code",
  MERCHANT: "Merchant",
  _ADVANCES:"Advances",
  RECORD_ADVANCE:"Record Advance"
};
